In [2]:
import pandas as pd

df_xgb = pd.read_csv('parallel_XGBoost_metrics.csv')
df_svr = pd.read_csv('parallel_svr_fitting_metrics.csv')
df_lstm = pd.read_csv('parallel_LSTM_metrics.csv')
df_gpr = pd.read_csv('parallel_gpr_metrics.csv')
df_linreg = pd.read_csv('parallel_linear_regression_metrics.csv')
persistence_df = pd.read_csv('persistence_rmse.csv')

In [3]:
df_xgb

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel XGBoost,5.843524,295.790597,0.027439,0.646711,0.072297,0.005227

In [4]:
df_svr

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel SVR (Fitting & Prediction),10.35585,111.808022,0.060923,0.43664,0.091296,0.008335

In [5]:
df_lstm

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel LSTM,82.978783,66.458301,0.033274,0.80084,0.054282,0.002947

In [6]:
df_gpr

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel GPR (Fitting & Prediction),289.78429,949.229096,0.025957,0.709593,0.065548,0.004297

In [7]:
df_linreg

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel Linear Regression,0.284749,0.012109,0.027569,0.809835,0.053042,0.002813

In [8]:
persistence_df

               Model     RMSE
0  Persistence Model  0.07137

In [9]:
final_df = pd.concat([df_xgb, df_svr, df_lstm, df_gpr, df_linreg], ignore_index=True)

In [10]:
final_df

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel XGBoost,5.843524,295.790597,0.027439,0.646711,0.072297,0.005227
1,Parallel SVR (Fitting & Prediction),10.355850,111.808022,0.060923,0.436640,0.091296,0.008335
2,Parallel LSTM,82.978783,66.458301,0.033274,0.800840,0.054282,0.002947
3,Parallel GPR (Fitting & Prediction),289.784290,949.229096,0.025957,0.709593,0.065548,0.004297
4,Parallel Linear Regression,0.284749,0.012109,0.027569,0.809835,0.053042,0.002813

In [11]:
rmse_value = persistence_df.loc[0, 'RMSE']
rmse_value

0.0713702957793329

In [12]:
final_df['skill_score'] = 1 - (final_df['RMSE'] / rmse_value)
final_df

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE,skill_score
0,Parallel XGBoost,5.843524,295.790597,0.027439,0.646711,0.072297,0.005227,-0.012990
1,Parallel SVR (Fitting & Prediction),10.355850,111.808022,0.060923,0.436640,0.091296,0.008335,-0.279185
2,Parallel LSTM,82.978783,66.458301,0.033274,0.800840,0.054282,0.002947,0.239427
3,Parallel GPR (Fitting & Prediction),289.784290,949.229096,0.025957,0.709593,0.065548,0.004297,0.081574
4,Parallel Linear Regression,0.284749,0.012109,0.027569,0.809835,0.053042,0.002813,0.256800

In [13]:
training_time_table = final_df[['Model','Training Time (s)']].sort_values(by=['Training Time (s)'])
prediction_time_table = final_df[['Model','Prediction Time (s)']].sort_values(by=['Prediction Time (s)'])
mae_table = final_df[['Model','MAE']].sort_values(by=['MAE'])
r_squared_table = final_df[['Model','R-squared']].sort_values(by=['R-squared'])
rmse_table = final_df[['Model','RMSE']].sort_values(by=['RMSE'])
mse_table = final_df[['Model','MSE']].sort_values(by=['MSE'])

In [14]:
training_time_table

                                 Model  Training Time (s)
4           Parallel Linear Regression           0.284749
0                     Parallel XGBoost           5.843524
1  Parallel SVR (Fitting & Prediction)          10.355850
2                        Parallel LSTM          82.978783
3  Parallel GPR (Fitting & Prediction)         289.784290

In [15]:
ranking_df = pd.DataFrame()
ranking_df["Model"] = final_df["Model"]

for col in ["Training Time (s)", "Prediction Time (s)", "MAE", "RMSE", "MSE"]:
    ranking_df[col] = final_df[col].rank(method="min", ascending=True).astype(int)

ranking_df["R-squared"] = final_df["R-squared"].rank(method="min", ascending=False).astype(int) 
ranking_df["skill_score"] = final_df["skill_score"].rank(method="min", ascending=False).astype(int) 

# Display the ranking table
ranking_df

,Model,Training Time (s),Prediction Time (s),MAE,RMSE,MSE,R-squared,skill_score
0,Parallel XGBoost,2,4,2,4,4,4,4
1,Parallel SVR (Fitting & Prediction),3,3,5,5,5,5,5
2,Parallel LSTM,4,2,4,2,2,2,2
3,Parallel GPR (Fitting & Prediction),5,5,1,3,3,3,3
4,Parallel Linear Regression,1,1,3,1,1,1,1

In [16]:
ranking_df["Row Average"] = ranking_df.iloc[:, 1:].mean(axis=1)

In [17]:
ranking_df.sort_values(by=['Row Average'])

,Model,Training Time (s),Prediction Time (s),MAE,RMSE,MSE,R-squared,skill_score,Row Average
4,Parallel Linear Regression,1,1,3,1,1,1,1,1.285714
2,Parallel LSTM,4,2,4,2,2,2,2,2.571429
3,Parallel GPR (Fitting & Prediction),5,5,1,3,3,3,3,3.285714
0,Parallel XGBoost,2,4,2,4,4,4,4,3.428571
1,Parallel SVR (Fitting & Prediction),3,3,5,5,5,5,5,4.428571