In [14]:
import pandas as pd

df_xgb = pd.read_csv('parallel_XGBoost_metrics.csv')
df_svr = pd.read_csv('parallel_svr_fitting_metrics.csv')
df_lstm = pd.read_csv('parallel_LSTM_metrics.csv')
df_gpr = pd.read_csv('parallel_gpr_metrics.csv')
df_ridge = pd.read_csv('parallel_ridge_regression_metrics.csv')
persistence_df = pd.read_csv('persistence_rmse.csv')

In [15]:
df_xgb

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel XGBoost,5.843524,295.790597,0.027439,0.646711,0.072297,0.005227

In [16]:
df_svr

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel SVR (Fitting & Prediction),10.35585,111.808022,0.060923,0.43664,0.091296,0.008335

In [17]:
df_lstm

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel LSTM,82.978783,66.458301,0.033274,0.80084,0.054282,0.002947

In [18]:
df_gpr

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel GPR (Fitting & Prediction),289.78429,949.229096,0.025957,0.709593,0.065548,0.004297

In [19]:
df_ridge

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel Ridge Regression,1.868803,2.487231,0.027289,0.722053,0.064127,0.004112

In [20]:
persistence_df

               Model     RMSE
0  Persistence Model  0.07137

In [21]:
final_df = pd.concat([df_xgb, df_svr, df_lstm, df_gpr, df_ridge], ignore_index=True)

In [22]:
final_df

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Parallel XGBoost,5.843524,295.790597,0.027439,0.646711,0.072297,0.005227
1,Parallel SVR (Fitting & Prediction),10.355850,111.808022,0.060923,0.436640,0.091296,0.008335
2,Parallel LSTM,82.978783,66.458301,0.033274,0.800840,0.054282,0.002947
3,Parallel GPR (Fitting & Prediction),289.784290,949.229096,0.025957,0.709593,0.065548,0.004297
4,Parallel Ridge Regression,1.868803,2.487231,0.027289,0.722053,0.064127,0.004112

In [23]:
rmse_value = persistence_df.loc[0, 'RMSE']
rmse_value

0.0713702957793329

In [24]:
final_df['skill_score'] = 1 - (final_df['RMSE'] / rmse_value)
final_df

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE,skill_score
0,Parallel XGBoost,5.843524,295.790597,0.027439,0.646711,0.072297,0.005227,-0.012990
1,Parallel SVR (Fitting & Prediction),10.355850,111.808022,0.060923,0.436640,0.091296,0.008335,-0.279185
2,Parallel LSTM,82.978783,66.458301,0.033274,0.800840,0.054282,0.002947,0.239427
3,Parallel GPR (Fitting & Prediction),289.784290,949.229096,0.025957,0.709593,0.065548,0.004297,0.081574
4,Parallel Ridge Regression,1.868803,2.487231,0.027289,0.722053,0.064127,0.004112,0.101494

In [25]:
ranking_df = pd.DataFrame()
ranking_df["Model"] = final_df["Model"]

for col in ["Training Time (s)", "Prediction Time (s)", "MAE", "RMSE", "MSE"]:
    ranking_df[col] = final_df[col].rank(method="min", ascending=True).astype(int)

ranking_df["R-squared"] = final_df["R-squared"].rank(method="min", ascending=False).astype(int) 
ranking_df["skill_score"] = final_df["skill_score"].rank(method="min", ascending=False).astype(int) 

# Display the ranking table
ranking_df

,Model,Training Time (s),Prediction Time (s),MAE,RMSE,MSE,R-squared,skill_score
0,Parallel XGBoost,2,4,3,4,4,4,4
1,Parallel SVR (Fitting & Prediction),3,3,5,5,5,5,5
2,Parallel LSTM,4,2,4,1,1,1,1
3,Parallel GPR (Fitting & Prediction),5,5,1,3,3,3,3
4,Parallel Ridge Regression,1,1,2,2,2,2,2

In [26]:
ranking_df["Row Average"] = ranking_df.iloc[:, 1:].mean(axis=1)

In [27]:
ranking_df.sort_values(by=['Row Average'])

,Model,Training Time (s),Prediction Time (s),MAE,RMSE,MSE,R-squared,skill_score,Row Average
4,Parallel Ridge Regression,1,1,2,2,2,2,2,1.714286
2,Parallel LSTM,4,2,4,1,1,1,1,2.000000
3,Parallel GPR (Fitting & Prediction),5,5,1,3,3,3,3,3.285714
0,Parallel XGBoost,2,4,3,4,4,4,4,3.571429
1,Parallel SVR (Fitting & Prediction),3,3,5,5,5,5,5,4.428571