In [16]:
import pandas as pd

df_xgb = pd.read_csv('XGBoost_metrics.csv')
df_lstm = pd.read_csv('LSTM_metrics.csv')
df_ridge = pd.read_csv('ridge_metrics.csv')
persistence_df = pd.read_csv('persistence_rmse.csv')

In [17]:
df_xgb

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,XGBoost,1.064968,0.067575,0.015356,0.868305,0.044141,0.001948

In [18]:
df_lstm

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,LSTM,1003.371662,5.492276,0.017471,0.856802,0.046028,0.002119

In [19]:
df_ridge

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,Ridge,0.058098,0.00539,0.027568,0.809839,0.053042,0.002813

In [20]:
persistence_df

               Model     RMSE
0  Persistence Model  0.07137

In [21]:
final_df = pd.concat([df_xgb, df_lstm, df_ridge], ignore_index=True)

In [22]:
final_df

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE
0,XGBoost,1.064968,0.067575,0.015356,0.868305,0.044141,0.001948
1,LSTM,1003.371662,5.492276,0.017471,0.856802,0.046028,0.002119
2,Ridge,0.058098,0.005390,0.027568,0.809839,0.053042,0.002813

In [23]:
rmse_value = persistence_df.loc[0, 'RMSE']
rmse_value

0.0713702957793329

In [24]:
final_df['skill_score'] = 1 - (final_df['RMSE'] / rmse_value)
final_df

,Model,Training Time (s),Prediction Time (s),MAE,R-squared,RMSE,MSE,skill_score
0,XGBoost,1.064968,0.067575,0.015356,0.868305,0.044141,0.001948,0.381522
1,LSTM,1003.371662,5.492276,0.017471,0.856802,0.046028,0.002119,0.355075
2,Ridge,0.058098,0.005390,0.027568,0.809839,0.053042,0.002813,0.256808

In [25]:
ranking_df = pd.DataFrame()
ranking_df["Model"] = final_df["Model"]

for col in ["Training Time (s)", "Prediction Time (s)", "MAE", "RMSE", "MSE"]:
    ranking_df[col] = final_df[col].rank(method="min", ascending=True).astype(int)

ranking_df["R-squared"] = final_df["R-squared"].rank(method="min", ascending=False).astype(int) 
ranking_df["skill_score"] = final_df["skill_score"].rank(method="min", ascending=False).astype(int) 

# Display the ranking table
ranking_df

,Model,Training Time (s),Prediction Time (s),MAE,RMSE,MSE,R-squared,skill_score
0,XGBoost,2,2,1,1,1,1,1
1,LSTM,3,3,2,2,2,2,2
2,Ridge,1,1,3,3,3,3,3

In [26]:
ranking_df["Row Average"] = ranking_df.iloc[:, 1:].mean(axis=1)

In [27]:
ranking_df.sort_values(by=['Row Average'])

,Model,Training Time (s),Prediction Time (s),MAE,RMSE,MSE,R-squared,skill_score,Row Average
0,XGBoost,2,2,1,1,1,1,1,1.285714
1,LSTM,3,3,2,2,2,2,2,2.285714
2,Ridge,1,1,3,3,3,3,3,2.428571